WIP Cleaning up messy implementation
AgileVentures/visualizer pull request #2
Opened 2017-01-19 14:24 UTC by tochman

Note that this is still very much a WIP!

2017-01-20 15:48 UTC, yggie requested changes

2017-01-20 15:48 UTC, yggie commented on app/controllers/pages_controller.rb
> -        render jason: {message: ex}
😂

2017-01-20 15:48 UTC, yggie commented on app/controllers/pages_controller.rb
> -        render jason: {message: ex}
on a more serious note, behaviour has changed without a change in tests, this is a good indication that certain tests are missing 😉

2017-01-20 15:48 UTC, yggie commented on app/modules/asset.rb
> +    @current_end_date = set_date(current_period[-1][0])
in many of these methods, there is an implicit dependency on certain instance variables to be defined. For example, this constructor will break if we move the line:

```ruby
  @service = service
```
to somewhere near the end of the method body. We can make this more explicit and also reduce dependency on the order of evaluation by making methods accept arguments explicitly, for example:

```ruby
@property = get_property

# can be changed to:

@property = get_property(service, params)
```

2017-01-20 15:48 UTC, yggie commented on app/modules/asset.rb
> +class Asset
I don’t think `Asset` is a great name, it doesn’t describe well the responsibilities of the object. The object looks like it is retrieving the analytics data for a specific time window. This data is then used to generate reports. Now based on my assumptions, I think a name like `AnalyticsWindowReport` would be more appropriate (or anything else, as long as it covers the responsibilities nicely).

2017-01-20 15:48 UTC, yggie commented on app/modules/asset.rb
> +    metrics = 'ga:sessions, ga:uniquePageviews'
a lot of hardcoded `ga: ` strings around, that makes us pretty coupled to Google Analytics. Now that is probably fine, but I just want to check if we are content with that coupling.

2017-01-20 15:48 UTC, yggie commented on app/modules/asset.rb
> +    ReportGenerator.generate(self)
With this method, the `ReportGenerator` is strongly coupled to the report asset itself. Would it make sense to move this logic higher up into the controller and let the controller decide how the reports will be generated? It feels like this method is mixing two different concerns into the class (most of the class is concerned with the in-memory _representation_ and _collection_ of the data, whereas this method is more about _presentation_)

2017-01-20 18:18 UTC, tochman commented on app/controllers/pages_controller.rb
> -        render jason: {message: ex}
Haha

2017-01-20 18:23 UTC, tochman commented on app/controllers/pages_controller.rb
> -        render jason: {message: ex}
A lot of test are missing. ;-)

2017-01-20 18:25 UTC, tochman commented on app/modules/asset.rb
> +class Asset
I agree. How about `AnalyticsPeriod`? I was considering `Period` (it was called that in my first version, but that also didn't feel right.

2017-01-20 18:26 UTC, tochman commented on app/modules/asset.rb
> +    @current_end_date = set_date(current_period[-1][0])
I see your point. I considered this approach but decided agains it. Good to get a second opinion and I concur.

2017-01-20 18:32 UTC, tochman commented on app/modules/asset.rb
> +    metrics = 'ga:sessions, ga:uniquePageviews'
At this point we are targeting the GA API so I would not worry about this for now.

2017-01-21 09:11 UTC, tochman commented
@yggie && @lollypop27 I’m aware that there are still quite a few possibilities to make the code better. It’s a matter of priorities at this stage in the project. What we are dealing with is a rough prototype so I would not spend too much time on getting every part in to excellent shape.

2017-01-21 14:26 UTC, yggie approved these changes

2017-01-23 13:16 UTC, lollypop27 commented
@tochman thanks for all this work

2017-01-23 13:18 UTC, lollypop27 approved these changes

2017-01-23 13:18 UTC, merged